Время эффекта порезано.
infinitystation/-tg-station pull request #71
Opened 2016-10-09 09:17 UTC by sir-duck

урезано время визуального эффекта
(плюсик над персонажем из-за вируса)

2016-10-09 17:35 UTC, ghost requested changes
Оттестировать, чтобы не было ошибок.

2016-10-09 17:36 UTC, sir-duck commented
там три строчки, которые я проверил на локалке =/

2016-10-09 17:40 UTC, Bill-Luxe commented on code/controllers/subsystem/voting.dm
>  			if("custom")
Добавь суда тоже world `<< sound('sound/effects/voted.ogg')`.

2016-10-13 11:01 UTC, Terror4000rus commented
Принимаю, в общем.

2016-10-13 11:01 UTC, merged